[env]
OPENCV_INCLUDE_PATHS = { value = "third_party/opencv-4.12-static/include", relative = true }
OPENCV_LINK_PATHS = { value = "third_party/opencv-4.12-static/x64/vc17/staticlib", relative = true }
OPENCV_LINK_LIBS = "static=opencv_features2d4120,static=opencv_imgproc4120,static=opencv_core4120,static=zlib"
OPENCV_DISABLE_PROBES = "pkg_config,cmake,vcpkg_cmake,vcpkg"
OPENCV_MSVC_CRT = "static"
